services:
  vm-jake:
    build:
      context: ./vm_openclaw
    image: vm-friends-vm-openclaw:latest
    container_name: vm-jake
    restart: unless-stopped

    volumes:
      - ./instances/vm-jake/openclaw:/root/.openclaw
    environment:
      TZ: Asia/Kolkata
      ROOT_PASSWORD: jake
  vm-jake2:
    build:
      context: ./vm_openclaw
    image: vm-friends-vm-openclaw:latest
    container_name: vm-jake2
    restart: unless-stopped

    volumes:
      - ./instances/vm-jake2/openclaw:/root/.openclaw
    environment:
      TZ: Asia/Kolkata
      ROOT_PASSWORD: jake2
  vm-ozden:
    build:
      context: ./vm_openclaw
    image: vm-friends-vm-openclaw:latest
    container_name: vm-ozden
    restart: unless-stopped
    ports:
      - "43817:22"
    volumes:
      - ./instances/vm-ozden/openclaw:/root/.openclaw
    environment:
      TZ: Asia/Kolkata
      ROOT_PASSWORD: ozden
  vm-ramsey:
    build:
      context: ./vm_openclaw
    image: vm-friends-vm-openclaw:latest
    container_name: vm-ramsey
    restart: unless-stopped
    ports:
      - "43817:22"
    volumes:
      - ./instances/vm-ramsey/openclaw:/root/.openclaw
    environment:
      TZ: Asia/Kolkata
      ROOT_PASSWORD: ramsey
