services:
  vm-ozden:
    build:
      context: ./vm_openclaw
    image: vm-friends-vm-openclaw:latest
    container_name: vm-ozden
    restart: unless-stopped
    ports:
      - "43817:22"
    volumes:
      - ./instances/vm-ozden/openclaw:/root/.openclaw
    environment:
      TZ: Asia/Kolkata
      ROOT_PASSWORD: ozden
  vm-ozden2:
    build:
      context: ./vm_openclaw
    image: vm-friends-vm-openclaw:latest
    container_name: vm-ozden2
    restart: unless-stopped
    ports:
      - "43820:22"
    volumes:
      - ./instances/vm-ozden2/openclaw:/root/.openclaw
    environment:
      TZ: Asia/Kolkata
      ROOT_PASSWORD: ozden2
  vm-pranav:
    build:
      context: ./vm_openclaw
    image: vm-friends-vm-openclaw:latest
    container_name: vm-pranav
    restart: unless-stopped
    ports:
      - "43818:22"
    volumes:
      - ./instances/vm-pranav/openclaw:/root/.openclaw
    environment:
      TZ: Asia/Kolkata
      ROOT_PASSWORD: pranav
  vm-reze:
    build:
      context: ./vm_nanobot
    image: vm-friends-vm-nanobot:latest
    container_name: vm-reze
    restart: unless-stopped
    ports:
      - "43819:22"
    volumes:
      - ./instances/vm-reze/nanobot:/root/.nanobot
    environment:
      TZ: Asia/Kolkata
      ROOT_PASSWORD: reze
